
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '\xa0\x91\x87\xfc\x19\xc4\x1b\\9\x95\xaa\x05\xbd!\xe2\x00'

_lr_action_items = {'LPAR':([0,1,2,3,4,5,6,8,10,11,12,13,14,15,16,],[1,7,-5,1,-2,-3,-9,7,-1,7,-7,7,-4,-6,-8,]),'SYMBOL':([0,1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,],[6,8,-5,6,-2,-3,-9,11,6,-1,6,-7,6,-4,-6,-8,]),'PARSE_FAILURE':([0,2,3,4,5,6,10,14,16,],[5,-5,5,-2,-3,-9,-1,-4,-8,]),'RPAR':([6,8,9,12,13,15,16,],[-9,-9,14,-7,16,-6,-8,]),'$end':([2,3,4,5,6,10,14,16,],[-5,0,-2,-3,-9,-1,-4,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s_expression':([0,1,3,8,11,13,],[2,9,2,12,12,15,]),'treebank':([0,],[3,]),'tree':([0,3,],[4,10,]),'s_expression_list':([8,11,],[13,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('treebank',2,'p_treebank_nt','sexpr.py',37),
  ('treebank',1,'p_treebank_t','sexpr.py',42),
  ('tree',1,'p_tree_failure','sexpr.py',46),
  ('tree',3,'p_tree_ptb','sexpr.py',50),
  ('tree',1,'p_tree','sexpr.py',55),
  ('s_expression_list',2,'p_s_expression_list_nt','sexpr.py',59),
  ('s_expression_list',1,'p_s_expression_list_t','sexpr.py',64),
  ('s_expression',4,'p_s_expression_nt','sexpr.py',68),
  ('s_expression',1,'p_s_expression_t','sexpr.py',73),
]
