#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-


import sys
from LabelledTree import *


# B Crabbé and M. Candito
#This implements the classical Magerman's head propagation tables
class PropagationTable:
    def __init__(self):
        self.dico = {}
        #marie : fast link from rule (lhs -> rhs) to head index in rhs
        self.rule_to_index = {}
        self.failing_rules = {}

    # head rules storage
    # key = lhs
    # val = list of couples (r, direction)
    #       where r is a list of categories [C1, C2, ... Cn]
    # for each couple ( [C1,C2...Cn] , direction) in the list,
    #    return the first element in rhs that is either C1, or C2... or Cn
    def add_mapping(self,lhs,value,direction):
        if not self.dico.has_key(lhs):
            self.dico[lhs] = []
        self.dico[lhs].append((value,direction))

    # marie : modif : 
    # aliases are now true aliases, i.e. it is transparent to use one or another
    # Example : if NC and NPP are aliases to N
    # before : find the first N, then if not found, find the first NC, then if not found find the first NPP
    # now : find the first symbol that is either a N, a NC or a NPP
    def add_aliases(self, symbol, aliaslist):
        for lhs in self.dico.keys():
            rules = self.dico[lhs]
            nrules = []
            for rule in rules:
                (r,dir) = rule
                if symbol in r:
                    r.extend(aliaslist)
                
    # Marie 
    # returns the index of head child, according to propagation table
    # cf_rule is a tuple, first elt = lhs symbol, other elements = the rhs symbols
    def find_child_index(self, cf_rule):
        lhs = cf_rule[0]
        if lhs not in self.dico:
            #sys.stderr.write('lhs not in propagation table:'+lhs)
            # Djame : note, normalement ca aussi c'est specifie par les regles
            # la derniere regle est une regle "defaut", genre prend le premier à gauche
            # ou le premier a droite
            # on va voir si on a une regle default
            # si la table a été converti par TBconvert elle contient 'DEFAULT'
            if 'DEFAULT' in self.dico:
            	lhs = 'DEFAULT'
            else:
            	return
        h_rules = self.dico[lhs]
        for h_rule in h_rules:
            (tags,d) = h_rule
            scan = cf_rule[1:]
            scanindex = range(len(scan))
            if d == "R": scanindex.reverse()
            # Marie : tags is now a list of disjunctive categories
            # : find the first element that matches any tag in tags
            for index in scanindex:
                if (scan[index] in tags or '*' in tags):
                    return index
        return None

    # Marie
    # returns the index of head child, according to propagation table
    # (searches for it in index dictionary, 
    #  or via find_child_index for first occurrence) 
    def get_child_index(self, cf_rule):
        # if such rule was never encountered before
        if not self.rule_to_index.has_key(cf_rule):
            i = self.find_child_index(cf_rule)
            if i == None:
                self.failing_rules[cf_rule] = self.failing_rules.get(cf_rule, 0) + 1
                return None
            self.rule_to_index[cf_rule] = i
            return i
        # else, such rule already encountered -> return stored index
        return self.rule_to_index[cf_rule]

    # statistics on head rule applications
    def stats(self):
        for rule in sorted(self.failing_rules.items(), lambda x,y: cmp(y[1], x[1]) or cmp(x[0], y[0])):
            print "MISSING HEAD FOR: (" + str(rule[1]) + ') ' + cf_rule_tostring(rule[0])

    def display_table(self):
        res = "----------------------------------------------------\n"
        for elt in sorted(self.dico.keys()):
            rules = self.dico[elt]
            for r in rules:
                (p,dir) = r
                res = res + elt+" ("+dir+") : "+" ".join(p) +"\n"
            res = res+"----------------------------------------------------\n"
        return res

#Dummy table for testing
def dummy_propag_table():
    ptable = PropagationTable()
    ptable.add_mapping("S",["VN"],"L")
    ptable.add_mapping("VN",["V"],"R")
    ptable.add_mapping("PP",["NP"],"L")
    ptable.add_mapping("NP",["N"],"L")
    ptable.add_aliases("V",["VINF","VFIN","VPP"])
    ptable.add_aliases("N",["NC","NPP"])
    ptable.add_aliases("S",["SENT"])
    return ptable
       

#Modified Arun and Keller's table for treebank with symset 4 
# marie : modified to cope with MFT treebank as well
# marie : modified to cope with new interpretation
#        ("lhs", [X, Y], R or L) means now :
#  in a rule with LHS as left-hand side, search for the first symbol that is either a X or a Y, starting from the Right (or from the Left)
def sym4_table():
    ptable = PropagationTable()
    #A&K Table
    ptable.add_mapping("AP",["A"],"R")
    ptable.add_mapping("AP",["N"],"R")
    ptable.add_mapping("AP",["V"],"R")
    # marie "(AP (COORD (C sinon) (AP (A normaux))))
    ptable.add_mapping("AP",["COORD"],"L")
    # marie : specific to MFT
    ptable.add_mapping("AP",["PREF"],"L")
    ptable.add_mapping("AdP",["ADV"],"R")
    ptable.add_mapping("AdP",["P"],"L")
    ptable.add_mapping("AdP",["P+D"],"L")
    ptable.add_mapping("AdP",["D"],"L")
    ptable.add_mapping("AdP",["C"],"L")
    # marie : specific to MFT
    ptable.add_mapping("AdP",["COORD"],"L")
    # mathieu : add PONCT exemple :
    # marie : to test this cf. sentence or vp coordination:
    # ptable.add_mapping("COORD",["VN", "V","C","PONCT"],"L")
    ptable.add_mapping("COORD",["C"],"L")
    ptable.add_mapping("COORD",["PONCT"],"L")
    ptable.add_mapping("COORD",["*"],"R") 
    # marie !! : pour le N c'est plutot le premier N à gauche
    # année 1999, mardi soir, filiale publicité, lendemain matin, case départ, volume record, plan média
    # "fin janvier" --> ?? contrexemple?
    # ==> crée pbs dans le cas de NP contenant appositions et mal reconnus
    # exemple : la Caixa, premiere caisse d'epargne espagnole
    # marie : P+PRO a une distribution de N
    # ptable.add_mapping("NP",["N","PRO","A","ADV"],"R")
    ptable.add_mapping("NP",["N"],"L")
    ptable.add_mapping("NP",["P+PRO"],"L")
    ptable.add_mapping("NP",["PRO"],"R")
    ptable.add_mapping("NP",["A"],"R")
    ptable.add_mapping("NP",["ADV"],"R")
    ptable.add_mapping("NP",["NP"],"L")
    ptable.add_mapping("NP",["*"],"R")
    # marie: inhib ben C : ptable.add_mapping("PP",["NP","N","V","ADV","A","CL","P"],"R")
    # original head rule from Arun (prep = head of PP)
    # ARUN : ptable.add_mapping("PP",['P', 'CL', 'A', 'ADV', 'V', 'N'], 'R')
    # marie : MODIFICATION OF ARUN : add PRO cf: (PP (PRO dont))
    #       MODIFICATION OF ARUN : add NP cf: (PP (NP (P+PRO auxquels)))
    ptable.add_mapping("PP",['P'],"R")
    ptable.add_mapping("PP",[ 'P+D'],"R")
    ptable.add_mapping("PP",[ 'CL'],"R")
    ptable.add_mapping("PP",[ 'A'],"R")
    ptable.add_mapping("PP",[ 'ADV'],"R")
    ptable.add_mapping("PP",[ 'V'],"R")
    ptable.add_mapping("PP",[ 'N'],"R")
    ptable.add_mapping("PP",[ 'PRO'],"R")
    ptable.add_mapping("PP",[ 'NP'],"R")
    # marie : specific to MFT
    ptable.add_mapping("PP",['COORD'],"L")
    # ARUN : ptable.add_mapping("SENT",["VN","V","NP","Srel","Ssub","Sint"],"L")
    # marie : MODIFICATION add COORD, VPinf, VPpart
    # mathieu : add I, AP
    ptable.add_mapping("SENT",["VN"],"L")
    ptable.add_mapping("SENT",["V"],"L")
    ptable.add_mapping("SENT",["NP"],"L")
    ptable.add_mapping("SENT",["Srel"],"L")
    ptable.add_mapping("SENT",["Ssub"],"L")
    ptable.add_mapping("SENT",["Sint"],"L")
    ptable.add_mapping("SENT",["VPinf"],"L")
    ptable.add_mapping("SENT",["VPpart"],"L")
    ptable.add_mapping("SENT",["COORD"],"L")
    ptable.add_mapping("SENT",[ "PP"],"L")
    ptable.add_mapping("SENT",[ "AdP"],"L")
    ptable.add_mapping("SENT",[ "AP"],"L")
    ptable.add_mapping("SENT",[ "I"],"L")
    ptable.add_mapping("Sint",["VN"],"L")
    ptable.add_mapping("Sint",["V"],"L")
    ptable.add_mapping("Sint",["*"],"R")
#marie    ptable.add_mapping("Srel",["VN","V"],"L")
# fausses relatives dont = "dont, en france, FO et la CFDT.
# mathieu : tu as mis PP pourquoi? moi j'avais rajouté NP
    ptable.add_mapping("Srel",["VN"],"L")
    ptable.add_mapping("Srel",["V"],"L")
    ptable.add_mapping("Srel",["NP"],"L")
    # marie : specific to MFT
    ptable.add_mapping("Srel",["COORD"],"L")
    # "C" ajouté pour cas de subordonnée elliptique (que toi)
    # et aussi pour le cas de structmod (Ssub contient alors (C) + (Sint))
    #ptable.add_mapping("Ssub",["VN","V"],"L")
    ptable.add_mapping("Ssub",["VN"],"L")
    ptable.add_mapping("Ssub",["V"],"L")
    ptable.add_mapping("Ssub",[ "C"],"L")
    ptable.add_mapping("Ssub",["*"],"R")
    ptable.add_mapping("VN",["V"],"R")
    ptable.add_mapping("VPinf",["VN"],"L")
    ptable.add_mapping("VPinf",["V"],"L")
    ptable.add_mapping("VPinf",["*"],"R")
    # mathieu : add AP : pourquoi? exemple?
    #ptable.add_mapping("VPpart",["VN","V"],"L")
    ptable.add_mapping("VPpart",["VN"],"L")
    ptable.add_mapping("VPpart",["V"],"L")
    ptable.add_mapping("VPpart",["AP"],"L")
    ptable.add_mapping("VPpart",["*"],"R")
    #Extension to symset 4
    ptable.add_aliases("V",["VIMP","VINF","VS","VPP","VPR"])
    # marie : added NNC (specific to MFT4)
    ptable.add_aliases("N",["NC","NPP","NNC"])
    ptable.add_aliases("C",["CS","CC"])
    ptable.add_aliases("CL",["CLS","CLO","CLR"])
    # marie : en fait P+PRO a une distribution de N (cf. est au sein du NP...)
    #ptable.add_aliases("P",["P+D","P+PRO"])
    # marie : inhibé car intégré directement supra    ptable.add_aliases("P",["P+D"])
    ptable.add_aliases("A",["ADJ","ADJWH"])
    ptable.add_aliases("ADV",["ADVWH"])
    ptable.add_aliases("PRO",["PROWH","PROREL"])
    ptable.add_aliases("D",["DET","DETWH"])
    # marie : specific to MFT (NC = non constituent coordinate)
    # -> on prend simplement le premier constituant...
    ptable.add_mapping("NC",["*"],"L")
    #        VP present dans le MFT (en cas de coord de VP)
    ptable.add_mapping("VP",["VN"],"L")
    return ptable

def cohead_table():
    ptable = PropagationTable()
    ptable.add_mapping("PP",["P","CL","A","ADV","V","N","NP"],"R")
    ptable.add_aliases("V",["VPP","VINF","VS","VIMP","VPR"])
    ptable.add_aliases("N",["NC","NPP"])
    ptable.add_aliases("C",["CS","CC"])
    ptable.add_aliases("CL",["CLS","CLO","CLR"])
    ptable.add_aliases("P",["P+D","P+PRO"])
    ptable.add_aliases("A",["ADJ","ADJWH"])
    ptable.add_aliases("ADV",["ADVWH"])
    ptable.add_aliases("PRO",["PROWH","PROREL"])
    ptable.add_aliases("D",["DET","DETWH"])
    return ptable

#++++++++++++++++
# propag tables derived from Ane's work

def gettable(headrulesname):
    ptable = PropagationTable()
    if headrulesname == 'Ane_FTB4':
	ptable.add_mapping('AP', ['A','ADJWH'], 'R')
	ptable.add_mapping('AP', ['ET'], 'R')
	ptable.add_mapping('AP', ['VPP'], 'R')
	ptable.add_mapping('AP', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('AdP', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('NP', ['NC','NPP','PRO','PROWH','PROREL'], 'L')
	ptable.add_mapping('NP', ['NP'], 'L')
	ptable.add_mapping('NP', ['A','ADJWH'], 'L')
	ptable.add_mapping('NP', ['AP'], 'L')
	ptable.add_mapping('NP', ['I'], 'L')
	ptable.add_mapping('NP', ['VPpart'], 'L')
	ptable.add_mapping('NP', ['ADV','ADVWH'], 'L')
	ptable.add_mapping('NP', ['AdP'], 'L')
	ptable.add_mapping('NP', ['ET'], 'L')
	ptable.add_mapping('NP', ['DET','DETWH'], 'L')
	ptable.add_mapping('PP', ['P'], 'L')
	ptable.add_mapping('PP', ['P+D'], 'L')
	ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
	ptable.add_mapping('Srel', ['VN'], 'R')
	ptable.add_mapping('Srel', ['AP'], 'R')
	ptable.add_mapping('Srel', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['VN'], 'R')
	ptable.add_mapping('Ssub', ['AP'], 'R')
	ptable.add_mapping('Ssub', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['PP'], 'R')
	ptable.add_mapping('Ssub', ['VPinf'], 'R')
	ptable.add_mapping('Ssub', ['Ssub'], 'R')
	ptable.add_mapping('Ssub', ['VPpart'], 'R')
	ptable.add_mapping('Ssub', ['A','ADJWH'], 'R')
	ptable.add_mapping('Ssub', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('Sint', ['VN'], 'R')
	ptable.add_mapping('Sint', ['AP'], 'R')
	ptable.add_mapping('Sint', ['NP'], 'R')
	ptable.add_mapping('Sint', ['PP'], 'R')
	ptable.add_mapping('Sint', ['VPinf'], 'R')
	ptable.add_mapping('Sint', ['Ssub'], 'R')
	ptable.add_mapping('Sint', ['VPpart'], 'R')
	ptable.add_mapping('Sint', ['A','ADJWH'], 'R')
	ptable.add_mapping('Sint', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('VPinf', ['VN'], 'L')
	ptable.add_mapping('VPinf', ['V','VIMP','VINF','VPP','VPR','VS'], 'L')
	ptable.add_mapping('VPpart', ['VPP','VPR'], 'L')
	ptable.add_mapping('VPpart', ['VN'], 'L')
	ptable.add_mapping('VN', ['V','VIMP','VINF','VPP','VPR','VS'], 'R')
	ptable.add_mapping('VN', ['VPinf'], 'R')
	ptable.add_mapping('COORD', ['CC','PONCT','CS'], 'L')
	ptable.add_mapping('SENT', ['VN'], 'R')
	ptable.add_mapping('SENT', ['AP'], 'R')
	ptable.add_mapping('SENT', ['NP'], 'R')
	ptable.add_mapping('SENT', ['Srel'], 'R')
	ptable.add_mapping('SENT', ['VPpart'], 'R')
	ptable.add_mapping('SENT', ['AdP'], 'R')
	ptable.add_mapping('SENT', ['I'], 'R')
	ptable.add_mapping('SENT', ['Ssub'], 'R')
	ptable.add_mapping('SENT', ['VPinf'], 'R')
	ptable.add_mapping('SENT', ['PP'], 'R')
	ptable.add_mapping('SENT', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('PONCT', ['PONCT'], 'R')
    elif headrulesname == 'Ane_FTBARUN':
	ptable.add_mapping('AP', ['A'], 'R')
	ptable.add_mapping('AP', ['ET'], 'R')
	ptable.add_mapping('AP', ['V'], 'R')
	ptable.add_mapping('AP', ['ADV'], 'R')
	ptable.add_mapping('AdP', ['ADV'], 'R')
	ptable.add_mapping('NP', ['N','PRO'], 'L')
	ptable.add_mapping('NP', ['NP'], 'L')
	ptable.add_mapping('NP', ['A'], 'L')
	ptable.add_mapping('NP', ['AP'], 'L')
	ptable.add_mapping('NP', ['I'], 'L')
	ptable.add_mapping('NP', ['VPpart'], 'L')
	ptable.add_mapping('NP', ['ADV'], 'L')
	ptable.add_mapping('NP', ['AdP'], 'L')
	ptable.add_mapping('NP', ['ET'], 'L')
	ptable.add_mapping('NP', ['D'], 'L')
	ptable.add_mapping('PP', ['P'], 'L')
	ptable.add_mapping('PP', ['PC'], 'L')
	ptable.add_mapping('Srel', ['VN'], 'R')
	ptable.add_mapping('Srel', ['AP'], 'R')
	ptable.add_mapping('Srel', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['VN'], 'R')
	ptable.add_mapping('Ssub', ['AP'], 'R')
	ptable.add_mapping('Ssub', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['PP'], 'R')
	ptable.add_mapping('Ssub', ['VPinf'], 'R')
	ptable.add_mapping('Ssub', ['Ssub'], 'R')
	ptable.add_mapping('Ssub', ['VPpart'], 'R')
	ptable.add_mapping('Ssub', ['A'], 'R')
	ptable.add_mapping('Ssub', ['ADV'], 'R')
	ptable.add_mapping('Sint', ['VN'], 'R')
	ptable.add_mapping('Sint', ['AP'], 'R')
	ptable.add_mapping('Sint', ['NP'], 'R')
	ptable.add_mapping('Sint', ['PP'], 'R')
	ptable.add_mapping('Sint', ['VPinf'], 'R')
	ptable.add_mapping('Sint', ['Ssub'], 'R')
	ptable.add_mapping('Sint', ['VPpart'], 'R')
	ptable.add_mapping('Sint', ['A'], 'R')
	ptable.add_mapping('Sint', ['ADV'], 'R')
	ptable.add_mapping('VPinf', ['VN'], 'L')
	ptable.add_mapping('VPinf', ['V'], 'L')
	ptable.add_mapping('VPpart', ['V'], 'L')
	ptable.add_mapping('VPpart', ['VN'], 'L')
	ptable.add_mapping('VN', ['V'], 'R')
	ptable.add_mapping('VN', ['VPinf'], 'R')
	ptable.add_mapping('COORD', ['C','PONCT'], 'L')
	ptable.add_mapping('SENT', ['VN'], 'R')
	ptable.add_mapping('SENT', ['AP'], 'R')
	ptable.add_mapping('SENT', ['NP'], 'R')
	ptable.add_mapping('SENT', ['Srel'], 'R')
	ptable.add_mapping('SENT', ['VPpart'], 'R')
	ptable.add_mapping('SENT', ['AdP'], 'R')
	ptable.add_mapping('SENT', ['I'], 'R')
	ptable.add_mapping('SENT', ['Ssub'], 'R')
	ptable.add_mapping('SENT', ['VPinf'], 'R')
	ptable.add_mapping('SENT', ['PP'], 'R')
	ptable.add_mapping('SENT', ['ADV'], 'R')
	ptable.add_mapping('PONCT', ['*'], 'L')
    elif headrulesname == 'Ane_MFT4':
	ptable.add_mapping('AP', ['A','ADJWH'], 'R')
	ptable.add_mapping('AP', ['ET'], 'R')
	ptable.add_mapping('AP', ['VPP'], 'R')
	ptable.add_mapping('AP', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('AP', ['PREF'], 'L')
	ptable.add_mapping('AP', ['COORD'], 'L')
	ptable.add_mapping('AdP', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('AdP', ['COORD'], 'L')
	ptable.add_mapping('NP', ['NCC','NPP','PRO','PROWH','PROREL'], 'L')
	ptable.add_mapping('NP', ['NP'], 'L')
	ptable.add_mapping('NP', ['A','ADJWH'], 'L')
	ptable.add_mapping('NP', ['AP'], 'L')
	ptable.add_mapping('NP', ['I'], 'L')
	ptable.add_mapping('NP', ['VPpart'], 'L')
	ptable.add_mapping('NP', ['ADV','ADVWH'], 'L')
	ptable.add_mapping('NP', ['AdP'], 'L')
	ptable.add_mapping('NP', ['ET'], 'L')
	ptable.add_mapping('NP', ['DET','DETWH'], 'L')
	ptable.add_mapping('NP', ['COORD'], 'L')
	ptable.add_mapping('PP', ['P'], 'L')
	ptable.add_mapping('PP', ['P+D'], 'L')
	ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
	ptable.add_mapping('PP', ['COORD'], 'L')
	ptable.add_mapping('Srel', ['VN'], 'R')
	ptable.add_mapping('Srel', ['AP'], 'R')
	ptable.add_mapping('Srel', ['NP'], 'R')
	ptable.add_mapping('Srel', ['COORD'], 'L')
	ptable.add_mapping('Ssub', ['VN'], 'R')
	ptable.add_mapping('Ssub', ['AP'], 'R')
	ptable.add_mapping('Ssub', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['PP'], 'R')
	ptable.add_mapping('Ssub', ['VPinf'], 'R')
	ptable.add_mapping('Ssub', ['Ssub'], 'R')
	ptable.add_mapping('Ssub', ['VPpart'], 'R')
	ptable.add_mapping('Ssub', ['A','ADJWH'], 'R')
	ptable.add_mapping('Ssub', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('Ssub', ['COORD'], 'L')
	ptable.add_mapping('Sint', ['VN'], 'R')
	ptable.add_mapping('Sint', ['AP'], 'R')
	ptable.add_mapping('Sint', ['NP'], 'R')
	ptable.add_mapping('Sint', ['PP'], 'R')
	ptable.add_mapping('Sint', ['VPinf'], 'R')
	ptable.add_mapping('Sint', ['Ssub'], 'R')
	ptable.add_mapping('Sint', ['VPpart'], 'R')
	ptable.add_mapping('Sint', ['A','ADJWH'], 'R')
	ptable.add_mapping('Sint', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('Sint', ['COORD'], 'L')
	ptable.add_mapping('VPinf', ['VN'], 'L')
	ptable.add_mapping('VPinf', ['V','VIMP','VINF','VPP','VPR','VS'], 'L')
	ptable.add_mapping('VPinf', ['COORD'], 'L')
	ptable.add_mapping('VPpart', ['VPP','VPR'], 'L')
	ptable.add_mapping('VPpart', ['VN'], 'L')
	ptable.add_mapping('VPpart', ['COORD'], 'L')
	ptable.add_mapping('VN', ['V','VIMP','VINF','VPP','VPR','VS'], 'R')
	ptable.add_mapping('VN', ['VPinf'], 'R')
	ptable.add_mapping('COORD', ['CC','PONCT','CS'], 'L')
	ptable.add_mapping('SENT', ['VN'], 'R')
	ptable.add_mapping('SENT', ['AP'], 'R')
	ptable.add_mapping('SENT', ['NP'], 'R')
	ptable.add_mapping('SENT', ['Srel'], 'R')
	ptable.add_mapping('SENT', ['VPpart'], 'R')
	ptable.add_mapping('SENT', ['AdP'], 'R')
	ptable.add_mapping('SENT', ['I'], 'R')
	ptable.add_mapping('SENT', ['Ssub'], 'R')
	ptable.add_mapping('SENT', ['VPinf'], 'R')
	ptable.add_mapping('SENT', ['PP'], 'R')
	ptable.add_mapping('SENT', ['ADV','ADVWH'], 'R')
	ptable.add_mapping('PONCT', ['PONCT'], 'R')
	ptable.add_mapping('NC', ['*'], 'L')
	ptable.add_mapping('VP', ['VN'], 'L')
    elif headrulesname == 'Ane_MFTMIN':
	ptable.add_mapping('AP', ['A'], 'R')
	ptable.add_mapping('AP', ['ET'], 'R')
	ptable.add_mapping('AP', ['VPpart','V'], 'R')
	ptable.add_mapping('AP', ['ADV'], 'R')
	ptable.add_mapping('AP', ['COORD'], 'L')
	ptable.add_mapping('AP', ['PREF'], 'L')
	ptable.add_mapping('AdP', ['ADV'], 'R')
	ptable.add_mapping('AdP', ['COORD'], 'L')
	ptable.add_mapping('NP', ['N','PRO'], 'L')
	ptable.add_mapping('NP', ['NP'], 'L')
	ptable.add_mapping('NP', ['A'], 'L')
	ptable.add_mapping('NP', ['AP'], 'L')
	ptable.add_mapping('NP', ['I'], 'L')
	ptable.add_mapping('NP', ['VPpart'], 'L')
	ptable.add_mapping('NP', ['ADV'], 'L')
	ptable.add_mapping('NP', ['AdP'], 'L')
	ptable.add_mapping('NP', ['N'], 'L')
	ptable.add_mapping('NP', ['ET'], 'L')
	ptable.add_mapping('NP', ['D'], 'L')
	ptable.add_mapping('NP', ['COORD'], 'L')
	ptable.add_mapping('PP', ['P'], 'L')
	ptable.add_mapping('PP', ['P+D'], 'L')
	ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
	ptable.add_mapping('PP', ['COORD'], 'L')
	ptable.add_mapping('Srel', ['VN'], 'R')
	ptable.add_mapping('Srel', ['AP'], 'R')
	ptable.add_mapping('Srel', ['NP'], 'R')
	ptable.add_mapping('Srel', ['VN'], 'R')
	ptable.add_mapping('Srel', ['COORD'], 'L')
	ptable.add_mapping('Ssub', ['VN'], 'R')
	ptable.add_mapping('Ssub', ['AP'], 'R')
	ptable.add_mapping('Ssub', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['PP'], 'R')
	ptable.add_mapping('Ssub', ['VPinf'], 'R')
	ptable.add_mapping('Ssub', ['Ssub'], 'R')
	ptable.add_mapping('Ssub', ['VPpart'], 'R')
	ptable.add_mapping('Ssub', ['A'], 'R')
	ptable.add_mapping('Ssub', ['ADV'], 'R')
	ptable.add_mapping('Ssub', ['VN'], 'R')
	ptable.add_mapping('Sint', ['VN'], 'R')
	ptable.add_mapping('Sint', ['AP'], 'R')
	ptable.add_mapping('Sint', ['NP'], 'R')
	ptable.add_mapping('Sint', ['PP'], 'R')
	ptable.add_mapping('Sint', ['VPinf'], 'R')
	ptable.add_mapping('Sint', ['Ssub'], 'R')
	ptable.add_mapping('Sint', ['VPpart'], 'R')
	ptable.add_mapping('Sint', ['A'], 'R')
	ptable.add_mapping('Sint', ['ADV'], 'R')
	ptable.add_mapping('Sint', ['VN'], 'R')
	ptable.add_mapping('VPinf', ['VN'], 'L')
	ptable.add_mapping('VPinf', ['VPinf','V'], 'L')
	ptable.add_mapping('VPinf', ['VPpart','V'], 'L')
	ptable.add_mapping('VPinf', ['VN'], 'R')
	ptable.add_mapping('VPpart', ['VPpart','V'], 'L')
	ptable.add_mapping('VPpart', ['VN'], 'L')
	ptable.add_mapping('VN', ['VPpart','VPinf','V','VN'], 'R')
	ptable.add_mapping('VN', ['VPinf'], 'R')
	ptable.add_mapping('COORD', ['C','PONCT'], 'L')
	ptable.add_mapping('SENT', ['VN'], 'R')
	ptable.add_mapping('SENT', ['AP'], 'R')
	ptable.add_mapping('SENT', ['NP'], 'R')
	ptable.add_mapping('SENT', ['Srel'], 'R')
	ptable.add_mapping('SENT', ['VPpart'], 'R')
	ptable.add_mapping('SENT', ['AdP'], 'R')
	ptable.add_mapping('SENT', ['I'], 'R')
	ptable.add_mapping('SENT', ['Ssub'], 'R')
	ptable.add_mapping('SENT', ['VPinf'], 'R')
	ptable.add_mapping('SENT', ['PP'], 'R')
	ptable.add_mapping('SENT', ['ADV'], 'R')
	ptable.add_mapping('SENT', ['VN'], 'R')
	ptable.add_mapping('PONCT', ['*'], 'L')
	ptable.add_mapping('NC', ['*'], 'L')
	ptable.add_mapping('VP', ['VN'], 'L')
    elif headrulesname == 'Ane_MFTSCHLU':
	# Marie ajout 
        #ptable.add_mapping('AP', ['A','A_int'], 'R')
        ptable.add_mapping('AP', ['A','A_int','A_card'], 'R')
	ptable.add_mapping('AP', ['ET'], 'R')
	ptable.add_mapping('AP', ['VPpart','V_part'], 'R')
	ptable.add_mapping('AP', ['ADV','ADV_int'], 'R')
	ptable.add_mapping('AP', ['COORD','COORD_AP','COORD_unary','COORD_NP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('AP', ['PREF'], 'L')
	ptable.add_mapping('AP_int', ['A','A_int'], 'R')
	ptable.add_mapping('AP_int', ['ET'], 'R')
	ptable.add_mapping('AP_int', ['VPpart','V_part'], 'R')
	ptable.add_mapping('AP_int', ['ADV','ADV_int'], 'R')
	ptable.add_mapping('AP_int', ['COORD','COORD_AP','COORD_unary','COORD_NP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('AP_int', ['PREF'], 'L')
	ptable.add_mapping('AdP', ['ADV','ADV_int'], 'R')
	ptable.add_mapping('AdP', ['COORD','COORD_AdP','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('AdP_int', ['ADV','ADV_int'], 'R')
	ptable.add_mapping('AdP_int', ['COORD','COORD_AdP','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('NP', ['N','N_card','PRO','PRO_rel','PRO_int','PRO_card'], 'L')
	ptable.add_mapping('NP', ['CL'], 'L')
        # MARIE : ajout post Ane_MFTSCHLU
	ptable.add_mapping('NP', ['NP'], 'L')
	ptable.add_mapping('NP', ['A'], 'L')
	ptable.add_mapping('NP', ['AP'], 'L')
	ptable.add_mapping('NP', ['I'], 'L')
	ptable.add_mapping('NP', ['VPpart'], 'L')
	ptable.add_mapping('NP', ['ADV'], 'L')
	ptable.add_mapping('NP', ['AdP'], 'L')
	ptable.add_mapping('NP', ['N'], 'L')
	ptable.add_mapping('NP', ['ET'], 'L')
	ptable.add_mapping('NP', ['D'], 'L')
	ptable.add_mapping('NP', ['COORD','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('NP_rel', ['N','N_card','PRO','PRO_rel','P+PRO_rel','PRO_int','PRO_card'], 'L')
	ptable.add_mapping('NP_rel', ['NP'], 'L')
	ptable.add_mapping('NP_rel', ['A'], 'L')
	ptable.add_mapping('NP_rel', ['AP'], 'L')
	ptable.add_mapping('NP_rel', ['I'], 'L')
	ptable.add_mapping('NP_rel', ['VPpart'], 'L')
	ptable.add_mapping('NP_rel', ['ADV'], 'L')
	ptable.add_mapping('NP_rel', ['AdP'], 'L')
	ptable.add_mapping('NP_rel', ['N'], 'L')
	ptable.add_mapping('NP_rel', ['ET'], 'L')
	ptable.add_mapping('NP_rel', ['D'], 'L')
	ptable.add_mapping('NP_rel', ['COORD','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('NP_int', ['N','N_card','PRO','PRO_rel','PRO_int','PRO_card'], 'L')
	ptable.add_mapping('NP_int', ['NP'], 'L')
	ptable.add_mapping('NP_int', ['A'], 'L')
	ptable.add_mapping('NP_int', ['AP'], 'L')
	ptable.add_mapping('NP_int', ['I'], 'L')
	ptable.add_mapping('NP_int', ['VPpart'], 'L')
	ptable.add_mapping('NP_int', ['ADV'], 'L')
	ptable.add_mapping('NP_int', ['AdP'], 'L')
	ptable.add_mapping('NP_int', ['N'], 'L')
	ptable.add_mapping('NP_int', ['ET'], 'L')
	ptable.add_mapping('NP_int', ['D'], 'L')
	ptable.add_mapping('NP_int', ['COORD','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('PP', ['P'], 'L')
	ptable.add_mapping('PP', ['P+D'], 'L')
	ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
	ptable.add_mapping('PP', ['COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('PP_rel', ['P'], 'L')
	ptable.add_mapping('PP_rel', ['P+D'], 'L')
        # ajout marie
	#ptable.add_mapping('PP_rel', ['NP_rel','P+PRO_rel'], 'L')
        ptable.add_mapping('PP_rel', ['NP_rel','PRO_rel','P+PRO_rel'], 'L')
	ptable.add_mapping('PP_rel', ['COORD','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('PP_int', ['P'], 'L')
	ptable.add_mapping('PP_int', ['P+D'], 'L')
	ptable.add_mapping('PP_int', ['NP_int','P+PRO_int'], 'L')
	ptable.add_mapping('PP_int', ['COORD','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('Srel', ['VN_finite','COORD_VN_finite'], 'R')
	ptable.add_mapping('Srel', ['AP'], 'R')
	ptable.add_mapping('Srel', ['NP','NP_rel'], 'R')
	ptable.add_mapping('Srel', ['VN'], 'R')
	ptable.add_mapping('Srel', ['COORD','COORD_unary','COORD_NP','COORD_AP','COORD_PP','COORD_VPpart','COORD_VPinf','COORD_Srel','COORD_Sint','COORD_Ssub','COORD_VP','COORD_AdP','COORD_UC','COORD_NC'], 'L')
	ptable.add_mapping('Ssub', ['VN_finite','COORD_VN_finite'], 'R')
	# ajout marie
        ptable.add_mapping('Ssub', ['COORD_Ssub'], 'R')
	ptable.add_mapping('Ssub', ['AP'], 'R')
	ptable.add_mapping('Ssub', ['NP'], 'R')
	ptable.add_mapping('Ssub', ['PP'], 'R')
	ptable.add_mapping('Ssub', ['VPinf'], 'R')
	ptable.add_mapping('Ssub', ['Ssub'], 'R')
	ptable.add_mapping('Ssub', ['VPpart'], 'R')
	ptable.add_mapping('Ssub', ['A'], 'R')
	ptable.add_mapping('Ssub', ['ADV'], 'R')
	ptable.add_mapping('Ssub', ['VN'], 'R')
	ptable.add_mapping('Sint', ['VN_finite','COORD_VN_finite'], 'R')
	ptable.add_mapping('Sint', ['AP'], 'R')
	ptable.add_mapping('Sint', ['NP'], 'R')
	ptable.add_mapping('Sint', ['PP'], 'R')
	ptable.add_mapping('Sint', ['VPinf'], 'R')
	ptable.add_mapping('Sint', ['Ssub'], 'R')
	ptable.add_mapping('Sint', ['VPpart'], 'R')
	ptable.add_mapping('Sint', ['A'], 'R')
	ptable.add_mapping('Sint', ['ADV'], 'R')
	ptable.add_mapping('Sint', ['VN'], 'R')
	ptable.add_mapping('VPinf', ['VN_inf','VN'], 'L')
	ptable.add_mapping('VPinf', ['VPinf','V_inf'], 'L')
	ptable.add_mapping('VPinf', ['VPpart','V','COORD_VPinf','COORD_VN_inf','COORD'], 'L')
	ptable.add_mapping('VPpart', ['VPpart','V_part','V'], 'L')
	ptable.add_mapping('VPpart', ['VN_part','VN', 'COORD_VPpart','COORD_VN_part','COORD'], 'L')
        # pou nopropag...
	ptable.add_mapping('VN', ['V_finite','COORD','V_inf','V_part'], 'R')
	ptable.add_mapping('VN_finite', ['V_finite','VN_finite','COORD_VN_finite','COORD'], 'R')
	ptable.add_mapping('VN_inf', ['V_inf','VN_inf','COORD_VN_inf'], 'R')
	ptable.add_mapping('VN_part', ['V_part','VN_part','COORD_VN_part','COORD'], 'R')
	# ajout marie
        ptable.add_mapping('COORD', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_unary', ['C_C','PONCT'], 'L')
	# ajout marie 
        #ptable.add_mapping('COORD_NP', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_NP', ['C_C','PONCT','NP'], 'L')
	ptable.add_mapping('COORD_PP', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_AP', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_AdP', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_VPpart', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_VPinf', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_VP', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_Ssub', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_Srel', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_Sint', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_UC', ['C_C','PONCT'], 'L')
	ptable.add_mapping('COORD_NC', ['C_C','PONCT'], 'L')
	ptable.add_mapping('SENT', ['VN_finite','VN_inf','VN_part'], 'R')
	ptable.add_mapping('SENT', ['AP'], 'R')
	ptable.add_mapping('SENT', ['NP'], 'R')
	ptable.add_mapping('SENT', ['Srel'], 'R')
	ptable.add_mapping('SENT', ['VPpart'], 'R')
	ptable.add_mapping('SENT', ['AdP'], 'R')
	ptable.add_mapping('SENT', ['I'], 'R')
	ptable.add_mapping('SENT', ['Ssub'], 'R')
	ptable.add_mapping('SENT', ['VPinf'], 'R')
	ptable.add_mapping('SENT', ['PP'], 'R')
	ptable.add_mapping('SENT', ['ADV'], 'R')
	ptable.add_mapping('SENT', ['VN'], 'R')
        # ajout marie
	ptable.add_mapping('SENT', ['COORD_Sint','COORD_Ssub','COORD_unary','COORD_UC','COORD_NP','COORD_AP','COORD'], 'R')
	ptable.add_mapping('PONCT', ['*'], 'L')
	ptable.add_mapping('NC', ['*'], 'L')
	ptable.add_mapping('VP', ['VN_finite'], 'L')

    if headrulesname == 'ftb4.head.lisp':
        ptable.add_mapping('S1', ['SENT'], 'L')
        ptable.add_mapping('PONCT', ['PONCT'], 'R')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('Sint', ['AP'], 'R')
        ptable.add_mapping('Sint', ['NP'], 'R')
        ptable.add_mapping('Sint', ['PP'], 'R')
        ptable.add_mapping('Sint', ['VPinf'], 'R')
        ptable.add_mapping('Sint', ['Ssub'], 'R')
        ptable.add_mapping('Sint', ['VPpart'], 'R')
        ptable.add_mapping('Sint', ['A','ADJ','ADJWH'], 'R')
        ptable.add_mapping('Sint', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('VPpart', ['VPR','VPP'], 'L')
        ptable.add_mapping('VPpart', ['VN'], 'L')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('SENT', ['AP'], 'R')
        ptable.add_mapping('SENT', ['NP'], 'R')
        ptable.add_mapping('SENT', ['Srel'], 'R')
        ptable.add_mapping('SENT', ['VPpart'], 'R')
        ptable.add_mapping('SENT', ['AdP'], 'R')
        ptable.add_mapping('SENT', ['I'], 'R')
        ptable.add_mapping('SENT', ['Ssub'], 'R')
        ptable.add_mapping('SENT', ['VPinf'], 'R')
        ptable.add_mapping('SENT', ['PP'], 'R')
        ptable.add_mapping('SENT', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('COORD', ['CS','CC','PONCT'], 'L')
        ptable.add_mapping('AP', ['A','ADJ','ADJWH'], 'R')
        ptable.add_mapping('AP', ['ET'], 'R')
        ptable.add_mapping('AP', ['VPP'], 'R')
        ptable.add_mapping('AP', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('DEFAULT', ['*'], 'L')
        ptable.add_mapping('NP', ['NPP','PROREL','PRO','NC','PROWH'], 'L')
        ptable.add_mapping('NP', ['NP'], 'L')
        ptable.add_mapping('NP', ['A','ADJ','ADJWH'], 'L')
        ptable.add_mapping('NP', ['AP'], 'L')
        ptable.add_mapping('NP', ['I'], 'L')
        ptable.add_mapping('NP', ['VPpart'], 'L')
        ptable.add_mapping('NP', ['ADV','ADVWH'], 'L')
        ptable.add_mapping('NP', ['AdP'], 'L')
        ptable.add_mapping('NP', ['ET'], 'L')
        ptable.add_mapping('NP', ['DETWH','DET'], 'L')
        ptable.add_mapping('VPinf', ['VN'], 'L')
        ptable.add_mapping('VPinf', ['VIMP','VPR','VS','VINF','V','VPP'], 'L')
        ptable.add_mapping('PP', ['P'], 'L')
        ptable.add_mapping('PP', ['P+D'], 'L')
        ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('Ssub', ['AP'], 'R')
        ptable.add_mapping('Ssub', ['NP'], 'R')
        ptable.add_mapping('Ssub', ['PP'], 'R')
        ptable.add_mapping('Ssub', ['VPinf'], 'R')
        ptable.add_mapping('Ssub', ['Ssub'], 'R')
        ptable.add_mapping('Ssub', ['VPpart'], 'R')
        ptable.add_mapping('Ssub', ['A','ADJ','ADJWH'], 'R')
        ptable.add_mapping('Ssub', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('VN', ['VIMP','VPR','VS','VINF','V','VPP'], 'R')
        ptable.add_mapping('VN', ['VPinf'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['AP'], 'R')
        ptable.add_mapping('Srel', ['NP'], 'R')
        ptable.add_mapping('AdP', ['ADV','ADVWH'], 'R')
    if headrulesname == 'ftbmin.head.lisp':
        ptable.add_mapping('S1', ['SENT'], 'L')
        ptable.add_mapping('PONCT', ['*'], 'L')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('Sint', ['AP'], 'R')
        ptable.add_mapping('Sint', ['NP'], 'R')
        ptable.add_mapping('Sint', ['PP'], 'R')
        ptable.add_mapping('Sint', ['VPinf'], 'R')
        ptable.add_mapping('Sint', ['Ssub'], 'R')
        ptable.add_mapping('Sint', ['VPpart'], 'R')
        ptable.add_mapping('Sint', ['A'], 'R')
        ptable.add_mapping('Sint', ['ADV'], 'R')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('VPpart', ['VPpart','V'], 'L')
        ptable.add_mapping('VPpart', ['VN'], 'L')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('SENT', ['AP'], 'R')
        ptable.add_mapping('SENT', ['NP'], 'R')
        ptable.add_mapping('SENT', ['Srel'], 'R')
        ptable.add_mapping('SENT', ['VPpart'], 'R')
        ptable.add_mapping('SENT', ['AdP'], 'R')
        ptable.add_mapping('SENT', ['I'], 'R')
        ptable.add_mapping('SENT', ['Ssub'], 'R')
        ptable.add_mapping('SENT', ['VPinf'], 'R')
        ptable.add_mapping('SENT', ['PP'], 'R')
        ptable.add_mapping('SENT', ['ADV'], 'R')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('COORD', ['C','PONTC'], 'L')
        ptable.add_mapping('AP', ['A'], 'R')
        ptable.add_mapping('AP', ['ET'], 'R')
        ptable.add_mapping('AP', ['VPpart','V'], 'R')
        ptable.add_mapping('AP', ['ADV'], 'R')
        ptable.add_mapping('DEFAULT', ['*'], 'L')
        ptable.add_mapping('NP', ['PRO','N'], 'L')
        ptable.add_mapping('NP', ['NP'], 'L')
        ptable.add_mapping('NP', ['A'], 'L')
        ptable.add_mapping('NP', ['AP'], 'L')
        ptable.add_mapping('NP', ['I'], 'L')
        ptable.add_mapping('NP', ['VPpart'], 'L')
        ptable.add_mapping('NP', ['ADV'], 'L')
        ptable.add_mapping('NP', ['AdP'], 'L')
        ptable.add_mapping('NP', ['N'], 'L')
        ptable.add_mapping('NP', ['ET'], 'L')
        ptable.add_mapping('NP', ['D'], 'L')
        ptable.add_mapping('VPinf', ['VN'], 'L')
        ptable.add_mapping('VPinf', ['VPinf','V'], 'L')
        ptable.add_mapping('VPinf', ['VPpart','V'], 'L')
        ptable.add_mapping('VPinf', ['VN'], 'R')
        ptable.add_mapping('PP', ['P'], 'L')
        ptable.add_mapping('PP', ['P+D'], 'L')
        ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('Ssub', ['AP'], 'R')
        ptable.add_mapping('Ssub', ['NP'], 'R')
        ptable.add_mapping('Ssub', ['PP'], 'R')
        ptable.add_mapping('Ssub', ['VPinf'], 'R')
        ptable.add_mapping('Ssub', ['Ssub'], 'R')
        ptable.add_mapping('Ssub', ['VPpart'], 'R')
        ptable.add_mapping('Ssub', ['A'], 'R')
        ptable.add_mapping('Ssub', ['ADV'], 'R')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('VN', ['VN','VPinf','VPpart','V'], 'R')
        ptable.add_mapping('VN', ['VPinf'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['AP'], 'R')
        ptable.add_mapping('Srel', ['NP'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('AdP', ['ADV'], 'R')
    if headrulesname == 'ftbschlu.head.lisp':
        ptable.add_mapping('S1', ['SENT'], 'L')
        ptable.add_mapping('COORD_VN_finite', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_AdP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('Sint', ['COORD_VN_finite','VN_finite'], 'R')
        ptable.add_mapping('Sint', ['AP'], 'R')
        ptable.add_mapping('Sint', ['NP'], 'R')
        ptable.add_mapping('Sint', ['PP'], 'R')
        ptable.add_mapping('Sint', ['VPinf'], 'R')
        ptable.add_mapping('Sint', ['Ssub'], 'R')
        ptable.add_mapping('Sint', ['VPpart'], 'R')
        ptable.add_mapping('Sint', ['A'], 'R')
        ptable.add_mapping('Sint', ['ADV'], 'R')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('VPpart', ['V_part','VPpart'], 'L')
        ptable.add_mapping('VPpart', ['COORD_VPpart','VN_part','COORD_VN_part'], 'L')
        ptable.add_mapping('COORD_VN_part', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_AP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('AP_int', ['A','A_int'], 'R')
        ptable.add_mapping('AP_int', ['ET'], 'R')
        ptable.add_mapping('AP_int', ['V_part','VPpart'], 'R')
        ptable.add_mapping('AP_int', ['ADV_int','ADV'], 'R')
        ptable.add_mapping('AP_int', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('AP_int', ['PREF'], 'L')
        ptable.add_mapping('VP', ['VN_finite'], 'L')
        ptable.add_mapping('COORD_unary', ['C_C','PONCT'], 'L')
        ptable.add_mapping('VPinf', ['VN_inf'], 'L')
        ptable.add_mapping('VPinf', ['VPinf','V'], 'L')
        ptable.add_mapping('VPinf', ['VPpart','V','COORD_VN_inf','COORD_VPinf'], 'L')
        ptable.add_mapping('COORD_Srel', ['C_C','PONCT'], 'L')
        ptable.add_mapping('VN_inf', ['V_inf','VN_inf','COORD_VN_inf'], 'R')
        ptable.add_mapping('COORD_Sint', ['C_C','PONCT'], 'L')
        ptable.add_mapping('NP_int', ['PRO','PRO_rel','N','PRO_int','N_card','PRO_card'], 'L')
        ptable.add_mapping('NP_int', ['NP'], 'L')
        ptable.add_mapping('NP_int', ['A'], 'L')
        ptable.add_mapping('NP_int', ['AP'], 'L')
        ptable.add_mapping('NP_int', ['I'], 'L')
        ptable.add_mapping('NP_int', ['VPpart'], 'L')
        ptable.add_mapping('NP_int', ['ADV'], 'L')
        ptable.add_mapping('NP_int', ['AdP'], 'L')
        ptable.add_mapping('NP_int', ['N'], 'L')
        ptable.add_mapping('NP_int', ['ET'], 'L')
        ptable.add_mapping('NP_int', ['D'], 'L')
        ptable.add_mapping('NP_int', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('PP_int', ['P'], 'L')
        ptable.add_mapping('PP_int', ['P+D'], 'L')
        ptable.add_mapping('PP_int', ['P+PRO_int','NP_int'], 'L')
        ptable.add_mapping('PP_int', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('VN', ['VPinf'], 'R')
        ptable.add_mapping('Srel', ['COORD_VN_finite','VN_finite'], 'R')
        ptable.add_mapping('Srel', ['AP'], 'R')
        ptable.add_mapping('Srel', ['NP','NP_rel'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('AdP', ['ADV','ADV_int'], 'R')
        ptable.add_mapping('AdP', ['COORD_VPpart','COORD_AdP','COORD_unary','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('COORD_VPpart', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_NC', ['C_C','PONCT'], 'L')
        ptable.add_mapping('AdP_int', ['ADV','ADV_int'], 'R')
        ptable.add_mapping('AdP_int', ['COORD_VPpart','COORD_AdP','COORD_unary','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('COORD_NP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('SENT', ['VN_part','VN_finite','VN_inf'], 'R')
        ptable.add_mapping('SENT', ['AP'], 'R')
        ptable.add_mapping('SENT', ['NP'], 'R')
        ptable.add_mapping('SENT', ['Srel'], 'R')
        ptable.add_mapping('SENT', ['VPpart'], 'R')
        ptable.add_mapping('SENT', ['AdP'], 'R')
        ptable.add_mapping('SENT', ['I'], 'R')
        ptable.add_mapping('SENT', ['Ssub'], 'R')
        ptable.add_mapping('SENT', ['VPinf'], 'R')
        ptable.add_mapping('SENT', ['PP'], 'R')
        ptable.add_mapping('SENT', ['ADV'], 'R')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('NP_rel', ['PRO','PRO_rel','N','PRO_int','N_card','P+PRO_rel','PRO_card'], 'L')
        ptable.add_mapping('NP_rel', ['NP'], 'L')
        ptable.add_mapping('NP_rel', ['A'], 'L')
        ptable.add_mapping('NP_rel', ['AP'], 'L')
        ptable.add_mapping('NP_rel', ['I'], 'L')
        ptable.add_mapping('NP_rel', ['VPpart'], 'L')
        ptable.add_mapping('NP_rel', ['ADV'], 'L')
        ptable.add_mapping('NP_rel', ['AdP'], 'L')
        ptable.add_mapping('NP_rel', ['N'], 'L')
        ptable.add_mapping('NP_rel', ['ET'], 'L')
        ptable.add_mapping('NP_rel', ['D'], 'L')
        ptable.add_mapping('NP_rel', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('VPpart_rel', ['VPpart'], 'L')
        ptable.add_mapping('COORD_Ssub', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_PP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_VP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('AP', ['A','A_int'], 'R')
        ptable.add_mapping('AP', ['ET'], 'R')
        ptable.add_mapping('AP', ['V_part','VPpart'], 'R')
        ptable.add_mapping('AP', ['ADV','ADV_int'], 'R')
        ptable.add_mapping('AP', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('AP', ['PREF'], 'L')
        ptable.add_mapping('VN_part', ['VN_part','V_part','COORD_VN_part'], 'R')
        ptable.add_mapping('COORD_UC', ['C_C','PONCT'], 'L')
        ptable.add_mapping('DEFAULT', ['*'], 'L')
        ptable.add_mapping('VN_finite', ['COORD_VN_finite','V_finite','VN_finite'], 'R')
        ptable.add_mapping('PP_rel', ['P'], 'L')
        ptable.add_mapping('PP_rel', ['P+D'], 'L')
        ptable.add_mapping('PP_rel', ['NP_rel','P+PRO_rel'], 'L')
        ptable.add_mapping('PP_rel', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('NP', ['PRO','PRO_rel','N','PRO_int','N_card','PRO_card'], 'L')
        ptable.add_mapping('NP', ['NP'], 'L')
        ptable.add_mapping('NP', ['A'], 'L')
        ptable.add_mapping('NP', ['AP'], 'L')
        ptable.add_mapping('NP', ['I'], 'L')
        ptable.add_mapping('NP', ['VPpart'], 'L')
        ptable.add_mapping('NP', ['ADV'], 'L')
        ptable.add_mapping('NP', ['AdP'], 'L')
        ptable.add_mapping('NP', ['N'], 'L')
        ptable.add_mapping('NP', ['ET'], 'L')
        ptable.add_mapping('NP', ['D'], 'L')
        ptable.add_mapping('NP', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('PP', ['P'], 'L')
        ptable.add_mapping('PP', ['P+D'], 'L')
        ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
        ptable.add_mapping('PP', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('Ssub', ['COORD_VN_finite','VN_finite'], 'R')
        ptable.add_mapping('Ssub', ['AP'], 'R')
        ptable.add_mapping('Ssub', ['NP'], 'R')
        ptable.add_mapping('Ssub', ['PP'], 'R')
        ptable.add_mapping('Ssub', ['VPinf'], 'R')
        ptable.add_mapping('Ssub', ['Ssub'], 'R')
        ptable.add_mapping('Ssub', ['VPpart'], 'R')
        ptable.add_mapping('Ssub', ['A'], 'R')
        ptable.add_mapping('Ssub', ['ADV'], 'R')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('COORD_VN_inf', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_VPinf', ['C_C','PONCT'], 'L')
    if headrulesname == 'mft4mft.head.lisp':
        ptable.add_mapping('S1', ['SENT'], 'L')
        ptable.add_mapping('NC', ['*'], 'L')
        ptable.add_mapping('NPC', ['NP'], 'L')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('Sint', ['AP'], 'R')
        ptable.add_mapping('Sint', ['NP'], 'R')
        ptable.add_mapping('Sint', ['PP'], 'R')
        ptable.add_mapping('Sint', ['VPinf'], 'R')
        ptable.add_mapping('Sint', ['Ssub'], 'R')
        ptable.add_mapping('Sint', ['VPpart'], 'R')
        ptable.add_mapping('Sint', ['A','ADJ','ADJWH'], 'R')
        ptable.add_mapping('Sint', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('Sint', ['COORD'], 'L')
        ptable.add_mapping('VPpart', ['VPR','VPP'], 'L')
        ptable.add_mapping('VPpart', ['VN'], 'L')
        ptable.add_mapping('VPpart', ['COORD'], 'L')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('SENT', ['AP'], 'R')
        ptable.add_mapping('SENT', ['NP'], 'R')
        ptable.add_mapping('SENT', ['Srel'], 'R')
        ptable.add_mapping('SENT', ['VPpart'], 'R')
        ptable.add_mapping('SENT', ['AdP'], 'R')
        ptable.add_mapping('SENT', ['I'], 'R')
        ptable.add_mapping('SENT', ['Ssub'], 'R')
        ptable.add_mapping('SENT', ['VPinf'], 'R')
        ptable.add_mapping('SENT', ['PP'], 'R')
        ptable.add_mapping('SENT', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('COORD', ['CS','CC'], 'L')
        ptable.add_mapping('VP', ['VPpart'], 'R')
        ptable.add_mapping('VP', ['VPinf'], 'R')
        ptable.add_mapping('VP', ['VN'], 'L')
        ptable.add_mapping('AP', ['A','ADJ','ADJWH'], 'R')
        ptable.add_mapping('AP', ['ET'], 'R')
        ptable.add_mapping('AP', ['VPP'], 'R')
        ptable.add_mapping('AP', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('AP', ['PREF'], 'L')
        ptable.add_mapping('AP', ['COORD'], 'L')
        ptable.add_mapping('DEFAULT', ['*'], 'L')
        ptable.add_mapping('NP', ['NPP','PROREL','PRO','PROWH','NNC'], 'L')
        ptable.add_mapping('NP', ['NP'], 'L')
        ptable.add_mapping('NP', ['A','ADJ','ADJWH'], 'L')
        ptable.add_mapping('NP', ['AP'], 'L')
        ptable.add_mapping('NP', ['I'], 'L')
        ptable.add_mapping('NP', ['VPpart'], 'L')
        ptable.add_mapping('NP', ['ADV','ADVWH'], 'L')
        ptable.add_mapping('NP', ['AdP'], 'L')
        ptable.add_mapping('NP', ['ET'], 'L')
        ptable.add_mapping('NP', ['DETWH','DET'], 'L')
        ptable.add_mapping('NP', ['COORD'], 'L')
        ptable.add_mapping('VPinf', ['VN'], 'L')
        ptable.add_mapping('VPinf', ['VIMP','VPR','VS','VINF','V','VPP'], 'L')
        ptable.add_mapping('VPinf', ['COORD'], 'L')
        ptable.add_mapping('PP', ['P'], 'L')
        ptable.add_mapping('PP', ['P+D'], 'L')
        ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
        ptable.add_mapping('PP', ['COORD'], 'L')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('Ssub', ['AP'], 'R')
        ptable.add_mapping('Ssub', ['NP'], 'R')
        ptable.add_mapping('Ssub', ['PP'], 'R')
        ptable.add_mapping('Ssub', ['VPinf'], 'R')
        ptable.add_mapping('Ssub', ['Ssub'], 'R')
        ptable.add_mapping('Ssub', ['VPpart'], 'R')
        ptable.add_mapping('Ssub', ['A','ADJ','ADJWH'], 'R')
        ptable.add_mapping('Ssub', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('Ssub', ['COORD'], 'L')
        ptable.add_mapping('VN', ['VIMP','VPR','VS','VINF','V','VPP'], 'R')
        ptable.add_mapping('VN', ['VPinf'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['AP'], 'R')
        ptable.add_mapping('Srel', ['NP'], 'R')
        ptable.add_mapping('Srel', ['COORD'], 'L')
        ptable.add_mapping('AdP', ['ADV','ADVWH'], 'R')
        ptable.add_mapping('AdP', ['COORD'], 'L')
    if headrulesname == 'mftmin.head.lisp':
        ptable.add_mapping('S1', ['SENT'], 'L')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('Sint', ['AP'], 'R')
        ptable.add_mapping('Sint', ['NP'], 'R')
        ptable.add_mapping('Sint', ['PP'], 'R')
        ptable.add_mapping('Sint', ['VPinf'], 'R')
        ptable.add_mapping('Sint', ['Ssub'], 'R')
        ptable.add_mapping('Sint', ['VPpart'], 'R')
        ptable.add_mapping('Sint', ['A'], 'R')
        ptable.add_mapping('Sint', ['ADV'], 'R')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('VPpart', ['VPpart','V'], 'L')
        ptable.add_mapping('VPpart', ['VN'], 'L')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('SENT', ['AP'], 'R')
        ptable.add_mapping('SENT', ['NP'], 'R')
        ptable.add_mapping('SENT', ['Srel'], 'R')
        ptable.add_mapping('SENT', ['VPpart'], 'R')
        ptable.add_mapping('SENT', ['AdP'], 'R')
        ptable.add_mapping('SENT', ['I'], 'R')
        ptable.add_mapping('SENT', ['Ssub'], 'R')
        ptable.add_mapping('SENT', ['VPinf'], 'R')
        ptable.add_mapping('SENT', ['PP'], 'R')
        ptable.add_mapping('SENT', ['ADV'], 'R')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('COORD', ['C','PONCT'], 'L')
        ptable.add_mapping('VP', ['VN'], 'L')
        ptable.add_mapping('AP', ['A'], 'R')
        ptable.add_mapping('AP', ['ET'], 'R')
        ptable.add_mapping('AP', ['VPpart','V'], 'R')
        ptable.add_mapping('AP', ['ADV'], 'R')
        ptable.add_mapping('AP', ['COORD'], 'L')
        ptable.add_mapping('AP', ['PREF'], 'L')
        ptable.add_mapping('DEFAULT', ['*'], 'L')
        ptable.add_mapping('NP', ['PRO','N'], 'L')
        ptable.add_mapping('NP', ['NP'], 'L')
        ptable.add_mapping('NP', ['A'], 'L')
        ptable.add_mapping('NP', ['AP'], 'L')
        ptable.add_mapping('NP', ['I'], 'L')
        ptable.add_mapping('NP', ['VPpart'], 'L')
        ptable.add_mapping('NP', ['ADV'], 'L')
        ptable.add_mapping('NP', ['AdP'], 'L')
        ptable.add_mapping('NP', ['N'], 'L')
        ptable.add_mapping('NP', ['ET'], 'L')
        ptable.add_mapping('NP', ['D'], 'L')
        ptable.add_mapping('NP', ['COORD'], 'L')
        ptable.add_mapping('VPinf', ['VN'], 'L')
        ptable.add_mapping('VPinf', ['VPinf','V'], 'L')
        ptable.add_mapping('VPinf', ['VPpart','V'], 'L')
        ptable.add_mapping('VPinf', ['VN'], 'R')
        ptable.add_mapping('PP', ['P'], 'L')
        ptable.add_mapping('PP', ['P+D'], 'L')
        ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
        ptable.add_mapping('PP', ['COORD'], 'L')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('Ssub', ['AP'], 'R')
        ptable.add_mapping('Ssub', ['NP'], 'R')
        ptable.add_mapping('Ssub', ['PP'], 'R')
        ptable.add_mapping('Ssub', ['VPinf'], 'R')
        ptable.add_mapping('Ssub', ['Ssub'], 'R')
        ptable.add_mapping('Ssub', ['VPpart'], 'R')
        ptable.add_mapping('Ssub', ['A'], 'R')
        ptable.add_mapping('Ssub', ['ADV'], 'R')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('VN', ['VN','VPinf','VPpart','V'], 'R')
        ptable.add_mapping('VN', ['VPinf'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['AP'], 'R')
        ptable.add_mapping('Srel', ['NP'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['COORD'], 'L')
        ptable.add_mapping('AdP', ['ADV'], 'R')
        ptable.add_mapping('AdP', ['COORD'], 'L')
    if headrulesname == 'mftschlu.head.lisp':
        ptable.add_mapping('S1', ['SENT'], 'L')
        ptable.add_mapping('COORD_VN_finite', ['C_C','PONCT'], 'L')
        ptable.add_mapping('NC', ['*'], 'L')
        ptable.add_mapping('COORD_AdP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('Sint', ['COORD_VN_finite','VN_finite'], 'R')
        ptable.add_mapping('Sint', ['AP'], 'R')
        ptable.add_mapping('Sint', ['NP'], 'R')
        ptable.add_mapping('Sint', ['PP'], 'R')
        ptable.add_mapping('Sint', ['VPinf'], 'R')
        ptable.add_mapping('Sint', ['Ssub'], 'R')
        ptable.add_mapping('Sint', ['VPpart'], 'R')
        ptable.add_mapping('Sint', ['A'], 'R')
        ptable.add_mapping('Sint', ['ADV'], 'R')
        ptable.add_mapping('Sint', ['VN'], 'R')
        ptable.add_mapping('VPpart', ['V_part','VPpart'], 'L')
        ptable.add_mapping('VPpart', ['COORD_VPpart','VN_part','COORD_VN_part'], 'L')
        ptable.add_mapping('COORD_VN_part', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_AP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('AP_int', ['A','A_int'], 'R')
        ptable.add_mapping('AP_int', ['ET'], 'R')
        ptable.add_mapping('AP_int', ['V_part','VPpart'], 'R')
        ptable.add_mapping('AP_int', ['ADV_int','ADV'], 'R')
        ptable.add_mapping('AP_int', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('AP_int', ['PREF'], 'L')
        ptable.add_mapping('VP', ['VN_finite'], 'L')
        ptable.add_mapping('COORD_unary', ['C_C','PONCT'], 'L')
        ptable.add_mapping('VPinf', ['VN_inf'], 'L')
        ptable.add_mapping('VPinf', ['VPinf','V'], 'L')
        ptable.add_mapping('VPinf', ['VPpart','V','COORD_VN_inf','COORD_VPinf'], 'L')
        ptable.add_mapping('COORD_Srel', ['C_C','PONCT'], 'L')
        ptable.add_mapping('VN_inf', ['V_inf','VN_inf','COORD_VN_inf'], 'R')
        ptable.add_mapping('COORD_Sint', ['C_C','PONCT'], 'L')
        ptable.add_mapping('NP_int', ['PRO','PRO_rel','N','PRO_int','N_card','PRO_card'], 'L')
        ptable.add_mapping('NP_int', ['NP'], 'L')
        ptable.add_mapping('NP_int', ['A'], 'L')
        ptable.add_mapping('NP_int', ['AP'], 'L')
        ptable.add_mapping('NP_int', ['I'], 'L')
        ptable.add_mapping('NP_int', ['VPpart'], 'L')
        ptable.add_mapping('NP_int', ['ADV'], 'L')
        ptable.add_mapping('NP_int', ['AdP'], 'L')
        ptable.add_mapping('NP_int', ['N'], 'L')
        ptable.add_mapping('NP_int', ['ET'], 'L')
        ptable.add_mapping('NP_int', ['D'], 'L')
        ptable.add_mapping('NP_int', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('PP_int', ['P'], 'L')
        ptable.add_mapping('PP_int', ['P+D'], 'L')
        ptable.add_mapping('PP_int', ['P+PRO_int','NP_int'], 'L')
        ptable.add_mapping('PP_int', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('Srel', ['COORD_VN_finite','VN_finite'], 'R')
        ptable.add_mapping('Srel', ['AP'], 'R')
        ptable.add_mapping('Srel', ['NP','NP_rel'], 'R')
        ptable.add_mapping('Srel', ['VN'], 'R')
        ptable.add_mapping('Srel', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('AdP', ['ADV','ADV_int'], 'R')
        ptable.add_mapping('AdP', ['COORD_VPpart','COORD_AdP','COORD_unary','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('COORD_VPpart', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_NC', ['C_C','PONCT'], 'L')
        ptable.add_mapping('PONCT', ['*'], 'L')
        ptable.add_mapping('AdP_int', ['ADV','ADV_int'], 'R')
        ptable.add_mapping('AdP_int', ['COORD_VPpart','COORD_AdP','COORD_unary','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('COORD_NP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('SENT', ['VN_part','VN_finite','VN_inf'], 'R')
        ptable.add_mapping('SENT', ['AP'], 'R')
        ptable.add_mapping('SENT', ['NP'], 'R')
        ptable.add_mapping('SENT', ['Srel'], 'R')
        ptable.add_mapping('SENT', ['VPpart'], 'R')
        ptable.add_mapping('SENT', ['AdP'], 'R')
        ptable.add_mapping('SENT', ['I'], 'R')
        ptable.add_mapping('SENT', ['Ssub'], 'R')
        ptable.add_mapping('SENT', ['VPinf'], 'R')
        ptable.add_mapping('SENT', ['PP'], 'R')
        ptable.add_mapping('SENT', ['ADV'], 'R')
        ptable.add_mapping('SENT', ['VN'], 'R')
        ptable.add_mapping('NP_rel', ['PRO','PRO_rel','N','PRO_int','N_card','P+PRO_rel','PRO_card'], 'L')
        ptable.add_mapping('NP_rel', ['NP'], 'L')
        ptable.add_mapping('NP_rel', ['A'], 'L')
        ptable.add_mapping('NP_rel', ['AP'], 'L')
        ptable.add_mapping('NP_rel', ['I'], 'L')
        ptable.add_mapping('NP_rel', ['VPpart'], 'L')
        ptable.add_mapping('NP_rel', ['ADV'], 'L')
        ptable.add_mapping('NP_rel', ['AdP'], 'L')
        ptable.add_mapping('NP_rel', ['N'], 'L')
        ptable.add_mapping('NP_rel', ['ET'], 'L')
        ptable.add_mapping('NP_rel', ['D'], 'L')
        ptable.add_mapping('NP_rel', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('VPpart_rel', ['VPpart'], 'L')
        ptable.add_mapping('COORD_Ssub', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_PP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_VP', ['C_C','PONCT'], 'L')
        ptable.add_mapping('AP', ['A','A_int'], 'R')
        ptable.add_mapping('AP', ['ET'], 'R')
        ptable.add_mapping('AP', ['V_part','VPpart'], 'R')
        ptable.add_mapping('AP', ['ADV','ADV_int'], 'R')
        ptable.add_mapping('AP', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('AP', ['PREF'], 'L')
        ptable.add_mapping('VN_part', ['VN_part','V_part','COORD_VN_part'], 'R')
        ptable.add_mapping('COORD_UC', ['C_C','PONCT'], 'L')
        ptable.add_mapping('DEFAULT', ['*'], 'L')
        ptable.add_mapping('VN_finite', ['COORD_VN_finite','V_finite','VN_finite'], 'R')
        ptable.add_mapping('PP_rel', ['P'], 'L')
        ptable.add_mapping('PP_rel', ['P+D'], 'L')
        ptable.add_mapping('PP_rel', ['NP_rel','P+PRO_rel'], 'L')
        ptable.add_mapping('PP_rel', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('NP', ['PRO','PRO_rel','N','PRO_int','N_card','PRO_card'], 'L')
        ptable.add_mapping('NP', ['NP'], 'L')
        ptable.add_mapping('NP', ['A'], 'L')
        ptable.add_mapping('NP', ['AP'], 'L')
        ptable.add_mapping('NP', ['I'], 'L')
        ptable.add_mapping('NP', ['VPpart'], 'L')
        ptable.add_mapping('NP', ['ADV'], 'L')
        ptable.add_mapping('NP', ['AdP'], 'L')
        ptable.add_mapping('NP', ['N'], 'L')
        ptable.add_mapping('NP', ['ET'], 'L')
        ptable.add_mapping('NP', ['D'], 'L')
        ptable.add_mapping('NP', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('PP', ['P'], 'L')
        ptable.add_mapping('PP', ['P+D'], 'L')
        ptable.add_mapping('PP', ['NP','P+PRO'], 'L')
        ptable.add_mapping('PP', ['COORD_VPpart','COORD_unary','COORD_AdP','COORD_UC','COORD_NC','COORD_Srel','COORD_NP','COORD_Sint','COORD_VPinf','COORD_Ssub','COORD_AP','COORD_PP','COORD_VP'], 'L')
        ptable.add_mapping('Ssub', ['COORD_VN_finite','VN_finite'], 'R')
        ptable.add_mapping('Ssub', ['AP'], 'R')
        ptable.add_mapping('Ssub', ['NP'], 'R')
        ptable.add_mapping('Ssub', ['PP'], 'R')
        ptable.add_mapping('Ssub', ['VPinf'], 'R')
        ptable.add_mapping('Ssub', ['Ssub'], 'R')
        ptable.add_mapping('Ssub', ['VPpart'], 'R')
        ptable.add_mapping('Ssub', ['A'], 'R')
        ptable.add_mapping('Ssub', ['ADV'], 'R')
        ptable.add_mapping('Ssub', ['VN'], 'R')
        ptable.add_mapping('COORD_VN_inf', ['C_C','PONCT'], 'L')
        ptable.add_mapping('COORD_VPinf', ['C_C','PONCT'], 'L')
    return ptable
