
# sexprtab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.0'

_lr_method = 'LALR'

_lr_signature = 2136560953
    
_lr_action_items = {'LPAR':([0,1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,],[1,7,-5,1,-2,-3,-10,7,-1,7,-7,7,-9,-4,-6,-8,]),'SYMBOL':([0,1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,],[6,8,-5,6,-2,-3,-10,11,6,-1,6,-7,6,-9,-4,-6,-8,]),'PARSE_FAILURE':([0,2,3,4,5,6,10,14,15,17,],[5,-5,5,-2,-3,-10,-1,-9,-4,-8,]),'RPAR':([6,8,9,11,12,13,14,16,17,],[-10,14,15,14,-7,17,-9,-6,-8,]),'$end':([2,3,4,5,6,10,14,15,17,],[-5,0,-2,-3,-10,-1,-9,-4,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'s_expression':([0,1,3,8,11,13,],[2,9,2,12,12,16,]),'treebank':([0,],[3,]),'tree':([0,3,],[4,10,]),'s_expression_list':([8,11,],[13,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> treebank","S'",1,None,None,None),
  ('treebank -> treebank tree','treebank',2,'p_treebank_nt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',42),
  ('treebank -> tree','treebank',1,'p_treebank_t','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',47),
  ('tree -> PARSE_FAILURE','tree',1,'p_tree_failure','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',51),
  ('tree -> LPAR s_expression RPAR','tree',3,'p_tree_ptb','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',55),
  ('tree -> s_expression','tree',1,'p_tree','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',60),
  ('s_expression_list -> s_expression_list s_expression','s_expression_list',2,'p_s_expression_list_nt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',64),
  ('s_expression_list -> s_expression','s_expression_list',1,'p_s_expression_list_t','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',69),
  ('s_expression -> LPAR SYMBOL s_expression_list RPAR','s_expression',4,'p_s_expression_nt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',73),
  ('s_expression -> LPAR SYMBOL RPAR','s_expression',3,'p_s_expression_trace','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',85),
  ('s_expression -> SYMBOL','s_expression',1,'p_s_expression_t','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/sexpr.py',97),
]
