
# triplestab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.0'

_lr_method = 'LALR'

_lr_signature = -1308285224
    
_lr_action_items = {'SENTFORM':([13,34,],[21,-7,]),'LPAR':([3,7,8,12,21,30,39,48,],[5,10,11,20,28,40,46,54,]),'SURFDEPS':([22,35,44,],[30,-11,-10,]),'MINUS':([15,16,17,18,19,24,32,60,62,64,],[-14,-13,-16,-15,25,-12,42,62,66,62,]),'TOK':([10,11,15,16,17,18,20,23,25,28,33,40,42,46,49,54,61,62,66,68,69,],[15,19,-14,15,-16,-15,26,15,32,15,26,48,51,48,48,15,15,67,70,-19,-20,]),'VALID':([9,57,],[12,-6,]),'COMMA':([14,15,16,17,18,24,26,59,67,70,],[23,-14,-13,-16,-15,-12,33,61,-21,-22,]),'FEATS':([29,47,56,],[39,-18,-17,]),'DATE':([6,10,15,16,17,18,23,28,41,54,61,],[8,17,-14,17,-16,-15,17,17,-5,17,17,]),'RPAR':([15,16,17,18,24,26,27,28,29,31,36,38,40,43,46,47,49,50,51,52,53,55,56,58,63,64,65,67,68,69,70,],[-14,-13,-16,-15,-12,-9,34,35,37,41,44,45,47,-8,52,-18,-25,56,57,-27,58,-24,-17,-26,68,-23,69,-21,-19,-20,-22,]),'ID':([5,10,15,16,17,18,23,28,54,61,],[7,18,-14,18,-16,-15,18,18,18,18,]),'SENT':([0,1,37,45,],[3,3,-4,-3,]),'$end':([1,2,4,37,45,],[-2,0,-1,-4,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toklist':([10,16,23,28,54,61,],[14,24,31,36,60,64,]),'validlist':([20,33,],[27,43,]),'ident':([5,],[6,]),'sentence':([0,1,],[1,1,]),'surf_deps':([22,],[29,]),'sentence_form':([13,],[22,]),'tok':([10,16,23,28,54,61,],[16,16,16,16,16,16,]),'deplist':([40,46,49,],[50,53,55,]),'valid':([9,],[13,]),'deps':([40,46,49,],[49,49,49,]),'date':([6,],[9,]),'sentencebank':([0,1,],[2,4,]),'feat_item':([61,],[65,]),'feats':([29,],[38,]),'triple_item':([54,61,],[59,63,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentencebank","S'",1,None,None,None),
  ('sentencebank -> sentence sentencebank','sentencebank',2,'p_sentencebank_nt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',93),
  ('sentencebank -> sentence','sentencebank',1,'p_sentencebank_t','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',97),
  ('sentence -> SENT LPAR ident date valid sentence_form surf_deps feats RPAR','sentence',9,'p_sentence','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',101),
  ('sentence -> SENT LPAR ident date valid sentence_form surf_deps RPAR','sentence',8,'p_sentence_short','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',110),
  ('ident -> ID LPAR toklist COMMA toklist RPAR','ident',6,'p_id','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',117),
  ('date -> DATE LPAR TOK MINUS TOK MINUS TOK RPAR','date',8,'p_date','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',121),
  ('valid -> VALID LPAR validlist RPAR','valid',4,'p_validator','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',125),
  ('validlist -> TOK COMMA validlist','validlist',3,'p_valid_list','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',129),
  ('validlist -> TOK','validlist',1,'p_valid_list_end','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',133),
  ('sentence_form -> SENTFORM LPAR toklist RPAR','sentence_form',4,'p_sentence_form','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',137),
  ('sentence_form -> SENTFORM LPAR RPAR','sentence_form',3,'p_sentence_form_empty','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',141),
  ('toklist -> tok toklist','toklist',2,'p_sentence_nt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',145),
  ('toklist -> tok','toklist',1,'p_sentence_t','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',149),
  ('tok -> TOK','tok',1,'p_tokt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',153),
  ('tok -> ID','tok',1,'p_toki','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',157),
  ('tok -> DATE','tok',1,'p_tokd','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',161),
  ('surf_deps -> SURFDEPS LPAR deplist RPAR','surf_deps',4,'p_surf_deps','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',178),
  ('surf_deps -> SURFDEPS LPAR RPAR','surf_deps',3,'p_surf_deps_empty','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',185),
  ('deps -> TOK LPAR triple_item COMMA triple_item RPAR','deps',6,'p_deps','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',190),
  ('deps -> TOK LPAR triple_item COMMA feat_item RPAR','deps',6,'p_deps_bis','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',195),
  ('triple_item -> toklist MINUS TOK','triple_item',3,'p_mbr_dep','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',199),
  ('triple_item -> toklist MINUS MINUS TOK','triple_item',4,'p_mbr_dep_neg','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',204),
  ('feat_item -> toklist','feat_item',1,'p_mbr_cat','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',209),
  ('deplist -> deps deplist','deplist',2,'p_deplist_nt','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',213),
  ('deplist -> deps','deplist',1,'p_deplist_t','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',217),
  ('feats -> FEATS LPAR deplist RPAR','feats',4,'p_feats','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',221),
  ('feats -> FEATS LPAR RPAR','feats',3,'p_feats_empty','/Users/mcandito/Documents/OUTILS/probparse/statgram/src/triplesp.py',225),
]
